import test from 'node:test';
import assert from 'node:assert/strict';
import { RECORD_KEY, ORIGINAL_KEY, REPLACEMENT_KEY, MAX_BYTES, MAX_RECORDS, normalizeRecords, openStore, saveRecords, availability, createBackup, inspectBackup, previewImport, canonical, deleteKnownKeys } from '../assets/local-records.mjs';

const sample=(id='one')=>({id,product_id:'product-'+id,name:'저장한 제품',brand:'브랜드',reasons:['직접 선택'],selected_at:'2026-08-26T00:00:00.000Z'});
function storage(raw=null){const values=new Map(raw===null?[]:[[RECORD_KEY,raw]]);return {getItem:(key)=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:(key)=>values.delete(key)};}

test('empty storage does not create records',()=>{const s=storage();assert.deepEqual(openStore(s).records,[]);assert.equal(s.getItem(RECORD_KEY),null);});
test('legacy fields, raw bytes and v2 provenance are preserved across reload',()=>{const raw=JSON.stringify([{...sample(),custom:{note:'keep'},reason:'old'}],null,2);const s=storage(raw);const opened=openStore(s);assert.equal(opened.mode,'persistent');assert.equal(s.getItem(ORIGINAL_KEY),raw);assert.equal(opened.records[0].schema_version,2);assert.equal(opened.records[0].product_data_version,'legacy-unknown');assert.equal(opened.records[0].score_version,'legacy-unknown');assert.deepEqual(opened.records[0].custom,{note:'keep'});assert.equal(openStore(s).migrated,false);});
test('corrupt, future, invalid and conflicting records never overwrite raw',()=>{for(const raw of ['{bad','{}','[null]',JSON.stringify([{...sample(),schema_version:99}]),JSON.stringify([sample(),{...sample(),name:'other'}])]){const s=storage(raw);assert.equal(openStore(s).mode,'memory');assert.equal(s.getItem(RECORD_KEY),raw);assert.equal(s.getItem(ORIGINAL_KEY),null);}});
test('failed backup retains raw and exposes normalized memory records',()=>{const raw=JSON.stringify([sample()]);const s=storage(raw);s.setItem=()=>{throw new Error('quota');};const opened=openStore(s);assert.equal(opened.mode,'memory');assert.equal(opened.records.length,1);assert.equal(s.getItem(RECORD_KEY),raw);});
test('unavailable storage fails safely',()=>{assert.equal(openStore({getItem(){throw new Error('denied');}}).mode,'memory');});
test('duplicates with identical IDs and content are collapsed without changing values',()=>{assert.equal(normalizeRecords([sample(),sample()]).length,1);assert.equal(normalizeRecords([sample('a'),sample('b')]).length,2);});
test('withdrawal preserves product name and prevents current availability claim',()=>{const r={...sample(),renewal_state:'withdrawn'};assert.equal(availability(r,[{id:r.product_id,public_allowed:true,rights_state:'approved'}]),'현재 이용 불가');assert.equal(r.name,'저장한 제품');assert.equal(availability(sample()),'현재 상품 정보 확인 불가');});
test('three export/import round trips preserve checksum and record content',async()=>{const date='2026-08-26T00:00:00.000Z';let records=normalizeRecords([sample('a'),sample('b')]);const first=await createBackup(records,date);for(let i=0;i<3;i++){const checked=await inspectBackup(JSON.stringify(await createBackup(records,date)));records=checked.records;assert.equal(checked.integrity,'verified');}assert.deepEqual(await createBackup(records,date),first);});
test('tampering, counts, unsupported versions, oversized inputs and prototype keys rejected',async()=>{const good=await createBackup([sample()]);const tampered=structuredClone(good);tampered.decisions[0].name='changed';await assert.rejects(inspectBackup(JSON.stringify(tampered)));await assert.rejects(inspectBackup(JSON.stringify({...good,count:5})));await assert.rejects(inspectBackup(JSON.stringify({...good,version:99})));await assert.rejects(inspectBackup(' '.repeat(MAX_BYTES+1)));await assert.rejects(inspectBackup('{"version":1,"decisions":[],"__proto__":{"polluted":true}}'));assert.throws(()=>normalizeRecords(Array.from({length:MAX_RECORDS+1},(_,i)=>sample(String(i)))));});
test('legacy backups are explicitly unverified and other services rejected',async()=>{const checked=await inspectBackup(JSON.stringify({version:3,decisions:[sample()]}));assert.equal(checked.integrity,'legacy_unverified');await assert.rejects(inspectBackup(JSON.stringify({version:3,format:'other',decisions:[]})));});
test('preview does not mutate; default merge retains conflicting existing content',()=>{const current=normalizeRecords([sample('a')]);const incoming=normalizeRecords([{...sample('a'),name:'different'},sample('b')]);const original=canonical(current);const p=previewImport(current,incoming);assert.equal(p.added,1);assert.equal(p.conflicts,1);assert.equal(p.records[0].name,'저장한 제품');assert.equal(canonical(current),original);const repeated=previewImport(p.records,incoming);assert.equal(repeated.records.length,2);assert.equal(repeated.added,0);});
test('replace shows removals, preserves raw recovery copy, blocks overwriting earlier recovery copy',()=>{const s=storage(JSON.stringify(normalizeRecords([sample('a')])));let opened=openStore(s);const p=previewImport(opened.records,[sample('b')],'replace');assert.equal(p.removed,1);const saved=saveRecords(s,opened.raw,p.records,{replace:true});assert.equal(saved.ok,true);assert.equal(s.getItem(REPLACEMENT_KEY),opened.raw);assert.equal(saveRecords(s,saved.raw,[sample('c')],{replace:true}).issue,'backup_exists');});
test('concurrent tab change blocks overwrite',()=>{const s=storage();const opened=openStore(s);s.setItem(RECORD_KEY,JSON.stringify([sample('other')]));assert.equal(saveRecords(s,opened.raw,[sample()]).issue,'conflict');assert.equal(JSON.parse(s.getItem(RECORD_KEY))[0].id,'other');});
test('item deletion is verified; failed writes never claim success',()=>{const s=storage(JSON.stringify(normalizeRecords([sample('a'),sample('b')])));const opened=openStore(s);const saved=saveRecords(s,opened.raw,opened.records.filter(x=>x.id!=='a'));assert.equal(saved.ok,true);assert.deepEqual(openStore(s).records.map(x=>x.id),['b']);s.setItem=()=>{};assert.equal(saveRecords(s,saved.raw,[]).ok,false);});
test('whole-library deletion includes recovery copies but never other applications',()=>{const s=storage('[]');s.setItem(ORIGINAL_KEY,'raw');s.setItem(REPLACEMENT_KEY,'raw');s.setItem('other-app','keep');assert.equal(deleteKnownKeys(s,[RECORD_KEY,ORIGINAL_KEY,REPLACEMENT_KEY]).ok,true);assert.equal(s.getItem('other-app'),'keep');s.setItem(RECORD_KEY,'[]');s.removeItem=()=>{};assert.equal(deleteKnownKeys(s,[RECORD_KEY]).ok,false);});
test('1,000 synthetic round trips: uniqueness, repeated merge and content preservation',async()=>{for(let i=0;i<1000;i++){const records=normalizeRecords([{...sample('persona-'+i),name:'합성 기록 '+i,metadata:{usage_period:i%2?'using':'not_started',repurchase:'undecided'}}]);const checked=await inspectBackup(JSON.stringify(await createBackup(records)));const merged=previewImport(records,checked.records);assert.equal(merged.records.length,1);assert.equal(canonical(merged.records),canonical(records));}});
