import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const read = (path) => readFileSync(resolve(root, path), 'utf8');
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const required = [
  'index.html', 'progress.html', 'offline.html', 'privacy.html', 'terms.html', 'support.html', 'about.html', 'cookies.html', 'advertising.html', 'ad-operations.html', 'ad-governance.html', 'privacy-choices.html', 'catalog-license.html', 'ads.txt', '.well-known/security.txt', '.nojekyll',
  'manifest.webmanifest', 'icon.svg', 'icon-192.svg', 'icon-512.svg', 'sw.js', 'robots.txt', 'sitemap.xml',
  'readiness.json', 'free-advanced-readiness.json', 'plus-readiness.json', 'stage1-v4-readiness.json', 'stage2-readiness.json', 'stage2-external-evidence.template.json', 'catalog-governance.json', 'ad-stage1-readiness.json', 'ad-stage2-readiness.json', 'ad-stage3-readiness.json', 'advertising-config.json', 'commercial-launch-readiness.json', 'commercial-launch-evidence.json', 'commercial-launch-evidence.template.json', 'evidence-v036.json',
  'guides/index.html', 'en/index.html', 'en/explorer.html', 'content/usage-guides.json', 'content/usage-guides.en.json', 'content/catalog-v4.json', 'content/ingredients-v4.json', 'content/shop-index-v1.json', 'assets/shopping-discovery-hero-v1.png', 'assets/free-advanced-app.mjs', 'assets/free-advanced-bootstrap.mjs', 'assets/catalog-v4.mjs', 'assets/stage2-v4.mjs', 'assets/catalog-en.mjs', 'assets/ad-policy.mjs', 'assets/consent-gate.mjs', 'assets/ad-router.mjs', 'assets/ad-metrics.mjs', 'assets/ad-optimizer.mjs', 'assets/adsense-formats.mjs', 'assets/ad-loader.mjs', 'assets/ad-stage1.css', 'assets/privacy-choices-page.mjs', 'assets/ad-operations-page.mjs', 'assets/ad-governance-page.mjs',
];
required.forEach((path) => assert(existsSync(resolve(root, path)), `필수 파일 없음: ${path}`));

const html = read('index.html');
const app = read('assets/free-advanced-app.mjs');
const bootstrap = read('assets/free-advanced-bootstrap.mjs');
const sw = read('sw.js');
const manifest = JSON.parse(read('manifest.webmanifest'));
const readiness = JSON.parse(read('readiness.json'));
const free = JSON.parse(read(readiness.free_advanced.status_file));
const plus = JSON.parse(read(readiness.plus_no_payment.status_file));
const evidence = JSON.parse(read(readiness.evidence_file));
const catalog = JSON.parse(read('content/catalog-v4.json'));
const shopIndex = JSON.parse(read('content/shop-index-v1.json'));
const ingredientCatalog = JSON.parse(read('content/ingredients-v4.json'));
const stageOneV4 = JSON.parse(read('stage1-v4-readiness.json'));
const stageTwoV4 = JSON.parse(read('stage2-readiness.json'));
const content = JSON.parse(read('content/usage-guides.json'));
const guideIndex = read('guides/index.html');
const englishIndex = read('en/index.html');
const englishExplorer = read('en/explorer.html');
const englishContent = JSON.parse(read('content/usage-guides.en.json'));
const progress = read('progress.html');
const privacy = read('privacy.html');
const terms = read('terms.html');
const support = read('support.html');
const sitemap = read('sitemap.xml');
const adConfig = JSON.parse(read('advertising-config.json'));
const adReadiness = JSON.parse(read('ad-stage1-readiness.json'));
const adStageTwo = JSON.parse(read('ad-stage2-readiness.json'));
const adStageThree = JSON.parse(read('ad-stage3-readiness.json'));
const commercialLaunch = JSON.parse(read('commercial-launch-readiness.json'));
const commercialEvidence = JSON.parse(read('commercial-launch-evidence.json'));
const adPolicy = read('assets/ad-policy.mjs');
const adRouter = read('assets/ad-router.mjs');
const adMetrics = read('assets/ad-metrics.mjs');
const adOptimizer = read('assets/ad-optimizer.mjs');
const adLoader = read('assets/ad-loader.mjs');
const advertising = read('advertising.html');
const adOperations = read('ad-operations.html');
const adGovernance = read('ad-governance.html');

const shoppingMode = html.includes('SHOP THE CATALOG');
assert(html.includes('<link rel="manifest" href="manifest.webmanifest">') && html.includes('serviceWorker.register'), '쇼핑 앱 또는 PWA 연결 누락');
assert(shoppingMode && ['id="heroSearch"', 'id="search"', 'id="scope"', 'id="category"', 'id="products"', 'id="compare"', '판매처 찾기'].every((token) => html.includes(token)), '쇼핑 검색·필터·비교·판매처 경로 누락');
assert(['global.oliveyoung.com', 'amazon.com', 'sephora.com', 'yesstyle.com', 'stylekorean.com'].every((host) => html.includes(host)), '다중 화장품 판매처 연결 누락');
assert(html.includes('제휴 수익 연결은 꺼져 있습니다') && html.includes('공식 서비스가 아닙니다'), '제휴 비활성 또는 독립 서비스 고지 누락');
assert(!/테스트 상품|테스트 자료|개발 진척|LAUNCH CHECK|95 \/ 100|올영스캐너 알파/.test(html), '소비자 화면에 개발·시험 문구가 노출됨');
assert(!html.includes('Google로 로그인') && !html.includes('account-login') && !html.includes('supabase'), '제공하지 않는 계정 기능이 소비자 화면에 남아 있음');
assert(!/<script\s+[^>]*src=["']https?:/i.test(html) && !/<link\s+[^>]*href=["']https?:[^>]*stylesheet/i.test(html), '외부 실행 코드 또는 글꼴 연결이 남아 있음');
assert(!html.includes('class="adsbygoogle"') && adConfig.enabled === false, '승인 전 외부 광고가 활성화됨');
assert(!app.includes('.innerHTML') && app.includes('textContent') && app.includes('MAX_BACKUP_BYTES') && app.includes('BACKUP_KEY_INVALID'), '안전 DOM 출력 또는 백업 검증 누락');
assert(['selectRoutineSlugs', 'filterGuides', 'upsertCheckin', 'makeBackup', 'parseBackup', 'saveRoutinePreset', 'compareRoutines', 'summarizeCheckins', 'upsertCollection', 'makeCalendarIcs', 'buildPrintReport', 'encryptBackup', 'decryptBackup'].every((name) => app.includes(`function ${name}`)), '무료 또는 Plus 핵심 함수 누락');
assert(!/stripe|checkout|paymentIntent|subscription/i.test(app) && !/₩|사이트에서 결제/.test(html), '사이트 내 결제 제외 경계 오류');
assert(bootstrap.includes('serviceWorker.register') && bootstrap.includes('mountFreeAdvancedApp') && bootstrap.includes('mountStage2V4'), '앱 시작·2단계 또는 서비스 워커 등록 누락');
assert(manifest.lang === 'ko-KR' && manifest.scope === './' && manifest.start_url === './#home' && manifest.shortcuts.length === 3, '무료 고급 PWA 정보 불일치');
assert(sw.includes("const RELEASE_VERSION = '2026-09-05-service-v0.38-shopping-marketplace'") && readiness.release_id === '2026-08-31-service-v0.36', '쇼핑 공개판 또는 기초 준비도 판번호 불일치');
assert(catalog.products.length === 2000 && new Set(catalog.products.map((row) => row.gtin)).size === 2000 && catalog.counts.human_reviewed_products === 0 && catalog.products.every((row) => row.formulation_versions?.length === 1), 'v4 실제 상품·처방 관찰 원장 수량·검수 분리 오류');
assert(ingredientCatalog.ingredients.length === 1000 && ingredientCatalog.human_editorial_complete === false, 'v4 성분명 원장 수량·사람 검수 분리 오류');
assert(stageOneV4.summary.total === 18 && stageOneV4.summary.done === 1 && stageOneV4.summary.strict_percent === 5.6 && stageOneV4.implemented_user_paths.percent === 100 && stageOneV4.facts.human_reviewed_products === 0 && stageOneV4.facts.android_devices_current_release === 0, 'v4 1단계 엄격 진척·외부 증거 분리 오류');
assert(stageTwoV4.strict.total === 12 && stageTwoV4.strict.done === 0 && stageTwoV4.development_contract.implemented === 12 && stageTwoV4.development_contract.percent === 100 && stageTwoV4.cards.every((card) => card.implemented === true) && Object.values(stageTwoV4.safe_defaults).every((value) => value === false || value === 0), 'v4 2단계 개발 계약·엄격 증거·안전 기본값 분리 오류');
assert(shopIndex.products.length === 2000 && shopIndex.products.every((row) => row.price === null && row.sellers.length === 0) && html.includes('상품 더 보기') && html.includes('function compareOpen'), '쇼핑 색인·가격/판매처 경계·비교·더보기 연결 누락');
assert(required.filter((path) => !['robots.txt', 'sitemap.xml', '.nojekyll', 'sw.js', 'commercial-launch-evidence.template.json'].includes(path)).every((path) => sw.includes(`'./${path}'`) || ['progress.html'].includes(path)), '오프라인 핵심 파일 누락');
assert(sw.includes('key.startsWith(CACHE_PREFIX)') && sw.includes('if (!allowed.includes(requested.href) && !isGuidePage) return'), '다른 앱·API 임시 저장 보호 누락');
assert(content.counts.guides === 24 && content.counts.sources === 7 && content.guides.every((guide) => guide.steps.length > 0 && guide.source_refs.length > 0), '완결 콘텐츠 수 또는 출처 연결 오류');
assert((guideIndex.match(/class="guide-card"/g) || []).length === 24 && (englishIndex.match(/class="guide-card"/g) || []).length === 24 && (sitemap.match(/<url>/g) || []).length === 36 && sitemap.includes('catalog-license.html') && sitemap.includes('en/explorer.html'), '한국어·영문 가이드 목록·영문 탐색기 또는 사이트맵 수 불일치');
assert(englishContent.status === 'ai_draft_human_review_pending' && englishContent.reviewed_by_human === false && englishContent.guides.length === 24 && englishIndex.includes('not operated, sponsored, or endorsed by Olive Young or another retailer'), '영문 탐색 초안 또는 독립성 경계 오류');
assert(englishExplorer.includes('2,000 records') && englishExplorer.includes('Purchasing remains unavailable') && englishExplorer.includes('catalog-en.mjs'), '영문 상품 탐색기 수량·구매 차단·연결 오류');
assert(free.code.total === 16 && free.code.verified === 16 && free.code.percent === 100 && free.code.cards.every((card) => ['VERIFIED','LIVE'].includes(card.status)), '무료 고급 코드 16/16 검증 상태 오류');
assert(free.operations.total === 4 && free.operations.done === 0 && free.operations.cards.every((card) => card.status === 'BLOCKED_EXTERNAL'), '외부 운영 증거를 자동 완료함');
assert(readiness.free_advanced.code_verified === free.code.verified && readiness.free_advanced.code_live === free.code.live && readiness.free_advanced.code_percent === free.code.percent, '전체 진척과 무료 고급 현황 대조 실패');
assert(plus.code.total === 12 && plus.code.verified === 12 && plus.code.percent === 100 && plus.payment.included === false && plus.payment.checkout_paths === 0 && plus.code.cards.every((card) => ['VERIFIED','LIVE'].includes(card.status)), '결제 제외 Plus 코드 12/12 상태 오류');
assert(readiness.plus_no_payment.code_verified === plus.code.verified && readiness.plus_no_payment.code_live === plus.code.live && readiness.plus_no_payment.payment_included === false, '전체 진척과 Plus 현황 대조 실패');
assert(evidence.release_id === readiness.release_id && evidence.automatic.total_tests === 120 && evidence.automatic.catalog_v4_unit_tests === 5 && evidence.automatic.stage2_unit_and_gate_tests === 13 && evidence.automatic.adsense_format_tests === 5 && evidence.automatic.link_audit_tests === 2 && evidence.automatic.publisher_quality_tests === 5 && evidence.automatic.cmp_signal_harness_tests === 4 && evidence.automatic.commercial_launch_gate_tests === 5 && evidence.automatic.android_device_selection_tests === 3 && evidence.automatic.free_advanced_unit_tests === 8 && evidence.automatic.plus_unit_tests === 14 && evidence.automatic.virtual_personas === 1000 && evidence.automatic.ad_safety_personas === 1000 && evidence.automatic.ad_stage2_regional_personas === 2000 && evidence.automatic.ad_stage3_advanced_scenarios === 20000 && evidence.automatic.account_required === false, '현재판 자동 증거 불일치');
assert(['pending','success'].includes(evidence.server.pages) && ['pending','success'].includes(evidence.server.codeql) && ['pending','success'].includes(evidence.server.public_verify), '현재판 공개 증거 상태 오류');
assert(privacy.includes('계정 로그인·분석 추적·서버 기록 저장을 제공하지 않으며') && privacy.includes('이름·이메일·전화번호·생년월일·자유서술은 받지 않습니다'), '현재 개인정보 처리 상태 누락');
assert(terms.includes('송출 중인 외부 광고') && terms.includes('제품 추천·실시간 가격·평점·인기 순위를 제공하지 않습니다'), '현재 무료판 수익·상품 경계 누락');
assert(support.includes('이 기기 기록 전체 삭제') && support.includes('다른 기기로 기록 옮기기'), '삭제·이동 안내 누락');
assert(progress.includes('개발 진척 대시보드') && progress.includes('콘텐츠 엄격 완료') && progress.includes('콘텐츠 자동 준비') && progress.includes('출시 외부 관문') && progress.includes('선택 Android 실제 확인'), '자동 준비와 외부 증거 분리 대시보드 누락');
assert(progress.includes('noindex,nofollow') && !sitemap.includes('progress.html'), '운영 대시보드 검색 제외 실패');
assert(adConfig.enabled === false && adConfig.publisher_id === 'ca-pub-2476023536699107' && adConfig.certified_cmp_ready === true && adConfig.operator_identity_confirmed === false, '확인되지 않은 광고 계정 또는 운영 조건을 활성화함');
assert(adReadiness.code.verified === 16 && adReadiness.code.live === 16 && adReadiness.code.percent === 100 && adReadiness.external_activation.done === 2, '광고 코드 준비와 확인된 ads.txt·CMP 증거 대조 실패');
assert(adStageTwo.code.verified === 24 && [0,24].includes(adStageTwo.code.live) && adStageTwo.code.percent === 100 && adStageTwo.external_activation.done === 2 && adStageTwo.active_providers.external === 0, '광고 2단계 코드·ads.txt·CMP·실제 제공자 운영을 섞음');
assert(readiness.advertising_stage_two.code_verified === adStageTwo.code.verified && readiness.advertising_stage_two.external_done === 2, '전체 진척과 광고 2단계 현황 대조 실패');
assert(adStageThree.code.verified === 32 && [0,32].includes(adStageThree.code.live) && adStageThree.code.percent === 100 && adStageThree.external_activation.done === 2 && adStageThree.supply_chain.done === 1 && adStageThree.active_operations.live_allocation_percent === 0, '광고 3단계 코드·ads.txt·CMP·실제 고급 운영을 섞음');
assert(readiness.advertising_stage_three.code_verified === adStageThree.code.verified && readiness.advertising_stage_three.external_done === 2 && readiness.advertising_stage_three.supply_chain_done === 1, '전체 진척과 광고 3단계 현황 대조 실패');
assert(commercialLaunch.technical.total === 12 && commercialLaunch.technical.verified === 12 && commercialLaunch.technical.percent === 100 && commercialLaunch.external.total === 12 && commercialLaunch.external.done === 3 && commercialLaunch.external.cards.filter((card) => card.status === 'VERIFIED_EXTERNAL').length === 3, '무료 상용화 기술 준비와 외부 증거를 섞음');
assert(commercialEvidence.site.adsense_registered === true && commercialEvidence.ads_txt.publisher_match === true && commercialEvidence.cmp.google_certified === true && commercialEvidence.cmp.eu_message_status === 'published' && commercialEvidence.cmp.us_state_message_status === 'published' && commercialEvidence.adsense.site_approved === false, '실제 AdSense 준비 중 상태 또는 확인된 웹사이트·ads.txt·CMP 증거 오류');
assert(readiness.commercial_launch.technical_verified === 12 && readiness.commercial_launch.external_done === 3, '전체 진척과 무료 상용화 현황 대조 실패');
assert(adConfig.schema_version === 3 && adConfig.stage_two.enabled === false && adConfig.stage_two.fail_closed === true && adConfig.stage_two.providers.filter((provider) => provider.external && provider.enabled).length === 0, '광고 2단계 기본 차단 설정 오류');
assert(adConfig.stage_two.placements['home-context'].format === 'display-responsive' && adConfig.stage_two.placements['guide-index-context'].format === 'multiplex' && adConfig.stage_two.placements['guide-detail-context'].format === 'in-article', 'AdSense 위치별 다형식 설정 오류');
assert(adConfig.auto_ads.enabled === false && adConfig.auto_ads.account_configuration_verified === false && adConfig.auto_ads.page_exclusions.includes('routine'), '민감 SPA 화면의 자동 광고 보호 오류');
assert(adConfig.stage_three.enabled === false && adConfig.stage_three.mode === 'shadow-only' && adConfig.stage_three.optimization.enabled === false && adConfig.stage_three.governance.approved_by.length === 0 && adConfig.stage_three.direct_campaigns.campaigns.length === 0, '광고 3단계 기본 차단 설정 오류');
assert(adPolicy.includes('forbidden_page_kinds') && adPolicy.includes('sanitizeAdContext') && adLoader.includes('showFallback') && adLoader.includes('canActivateAdvertising'), '광고 허용표·민감 문맥 제거·대체 화면 관문 누락');
assert(adRouter.includes('resolveRegionalPolicy') && adRouter.includes('selectProvider') && adRouter.includes('evaluateStopLoss') && adMetrics.includes('MAX_EVENTS = 200'), '지역·제공자 선택·자동 중단·제한 기록 누락');
assert(['parseAdsTxt', 'validateSupplyChain', 'evaluateTrafficQuality', 'enforceFrequencyCaps', 'selectDirectCampaign', 'selectMonetizationCandidate', 'evaluateAdvancedStopLoss', 'sanitizeAggregateRow', 'pruneAggregateRows', 'createRollbackFingerprint'].every((name) => adOptimizer.includes(`function ${name}`)), '공급망·부정 트래픽·캠페인·제한 공개·복구 함수 누락');
assert(adLoader.includes('selectMonetizationCandidate') && adLoader.includes("adTrafficSource !== 'operator-server'") && adLoader.includes('DIRECT_CREATIVE_ADAPTER_REQUIRED'), '광고 3단계 로더 연결 또는 외부 신뢰·직접 소재 차단 누락');
assert(advertising.includes('현재 상태: 외부 광고·제휴 링크 꺼짐') && advertising.includes('지역·종류·단가별 선택') && privacy.includes('광고 네트워크로 정보를 보내지 않습니다'), '광고·개인정보 현재 상태 고지 누락');
assert(adOperations.includes('noindex,nofollow') && adOperations.includes('이 기기 광고 운영 기록 삭제') && !sitemap.includes('ad-operations.html'), '광고 투명성 화면 검색 제외 또는 삭제 경로 누락');
assert(adGovernance.includes('noindex,nofollow') && adGovernance.includes('공급망 확인') && adGovernance.includes('최대 5%') && !sitemap.includes('ad-governance.html'), '광고 공급망·제한 공개 화면 검색 제외 또는 현재 상태 누락');

console.log(`[public-verify] PASS — 필수 ${required.length}파일, 광고 1단계 16/16·2단계 24/24·3단계 32/32, 공급망·부정 트래픽·캠페인·제한 공개와 외부 운영 분리`);
